### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by ehsan-ali-th** [NyanKiyoshi/latex-graphql-highlighter#1]
Package keyval Error: linebreaks undefined. \begin{gql}
Package minted Error: Missing Pygments output; \inputminted wasor may be using frozencache with a missing file. \end{gql}
No file example.aux.

Using Windows 11, TexStudio.

**Comment by ehsan-ali-th** [comment]
Solved with this: 

\usepackage[cache=false]{minted}

But then I get: Package keyval Error: linebreaks undefined. \begin{gql}

**Comment by NyanKiyoshi** [comment]
Hi @ehsan-ali-th,

Glad to hear you resolved the issue. For the error message, I pushed a fix at https://github.com/NyanKiyoshi/latex-graphql-highlighter/commit/b41fe80b4d32a6e123974c0a3e86db41023b7e78.
